version: '3'
services:
  pirigation-backend:
    build: ./pirigation-backend
    ports:
      - "3001:3001"
    volumes:
      - ./pirigation-backend:/server.py
    networks:
      - webnet

  pirigation-frontend:
    build: ./pirigation-frontend
    ports:
      - "80:80"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs:/etc/nginx/ssl/certs:ro
      - /etc/ssl/private:/etc/nginx/ssl/private:ro
    depends_on:
      - pirigation-backend
      - pirigation-frontend
    networks:
      - webnet

networks:
  webnet:
